<?php

namespace App\Enums;

enum InterestsEnum: string
{

case SORTS = 'SORTS';
case TRAVEL = 'TRAVEL';
case FASHION = 'FASHION';
case COOKING = 'COOKING';
case DRINKS = 'DRINKS';
case READING = 'READING';
case TECHNOLOGY = 'TECHNOLOGY';
case ARTSANDDESIGN = 'ARTS AND DESIGN';
case MUSIC = 'MUSIC';
case GAMING = 'GAMING';
case PHOTOGRAPHY = 'PHOTOGRAPHY';
case FILMANDTV = 'FILM AND TV';
case OUTDOORACTIVITIES = 'OUTDOOR ACTIVITIES';
case HEALTHANDFITNESS = 'HEALTH AND FITNESS';
case PETS = 'PETS';
case GARDENING = 'GARDENING';
case DIYANDHOMEIMPROVEMENT = 'DIY AND HOME IMPROVEMENT';
case PERSONALGROWTH = 'PERSONAL GROWTH';
case PODCASTS = 'PODCASTS';
case BEAUTYANDSKINCARE = 'BEAUTY AND SKIN CARE';
case ENVIRONMENTANDSUSTAINABILITY = 'ENVIRONMENT AND SUSTAINABILITY';
case SCIENCEANDEDUCATION = 'SCIENCE AND EDUCATION';
case OTHER = 'OTHER';
}
